### ISSUE TITLE
File upload workflow

### ISSUE THREAD

**Issue by hemebond** [hemebond/quaddicted#1]
What are the outcomes of the following workflows:

- New map entry ->
  - no existing file name or hash ->
    - create new map entry
  - file name exists ->
  - file hash exists ->

- Update map entry ->
  - Remove old file?
  - Point map entry to new file?
  - List all files as versions?

**Comment by SpiritQuaddicted** [comment]
My answers in bold, I hope I understood the questions correctly.

- New map entry ->
  - no existing file name or hash ->
    - create new map entry
  - file name exists ->
    **- Add other filename to entry as alternative**
  - file hash exists ->
    **- Tell user that the hash is already covered by other entry and suggest they edit that**

- Update map entry ->
  - Remove old file?
    **- No file will ever be removed, entry is bound to its hash anyways**
  - Point map entry to new file?
    **- Can't happen, the hash is what identifies an entry so the entry always references one specific file**
  - List all files as versions?
    **- I haven't thought about versions too deeply, it would be a nice thing to have a human friendly identifier per "thing humans care about" as opposed to the hashes. E. g. versions of a mod could all be "basename=modname" or something and have a "version=1.23", but then we might get fights about those basenames and what is official versions and what is unofficial. Also comments on a file might reference things specific to a specific version, mixing other versions into this could lead to confusion.**
    **- For the metadata changes it would be great to have a public history.**

**Comment by hemebond** [comment]
>   - file name exists ->
>     - Add other filename to entry as alternative

So a map entry will have multiple downloads available? Show a timestamp based on the oldest file in the upload?

>   - file hash exists ->
>     - Tell user that the hash is already covered by other entry and suggest they edit that

Okay, show error and direct them to the existing map entry.

>   - Remove old file?
>     - No file will ever be removed, entry is bound to its hash anyways

But map entries can have multiple downloads so should it not be added?

>   - Point map entry to new file?
>     - Can't happen, the hash is what identifies an entry so the entry always references one specific file

Moot if map entries can now have multiple downloads.

>   - List all files as versions?
>     - I haven't thought about versions too deeply, it would be a nice thing to have a human friendly identifier per "thing humans care about" as opposed to the hashes. E. g. versions of a mod could all be "basename=modname" or something and have a "version=1.23", but then we might get fights about those basenames and what is official versions and what is unofficial. Also comments on a file might reference things specific to a specific version, mixing other versions into this could lead to confusion.

If map entries have multiple downloads listed then each download is a version.

>   -  - For the metadata changes it would be great to have a public history.

That's doable.

**Comment by SpiritQuaddicted** [comment]
An entry always describes exactly one file, with a file being a bunch of bytes.

Multiple file*names* can exist because people like to give the *same* file (same hash, thus same entry) different names. For example sometimes people use the same basename.zip for a persistent download URL and also have the same file named basename_v123.zip as versioned URL. In that case the entry would not just have one name but ["basename.zip", "basename_v123.zip"] or the filenames themselves would need to become tags. I don't know yet how to decide which filename should be the downloaded filename...

**Comment by hemebond** [comment]
### ORM

`Map.package` is a foreign key to a `Package`.

#### New Map Listing
A new map listing is created when a user uploads a map package (.zip)
```yaml
title: My ABC Map # unique
name: abc # auto, mutable, unique
# a foreign key to the package
package:
  name: abc # auto
  hash: 00f... # auto
  modified: 2019-12-01T01:00:00Z # auto, modified timestamp of newest file in package
  # These files could be visible as a simple directory listing to allow for indexing by search engines
  urls:
  - //quaddicted.com/files/by-sha256/0/00f.../abc.zip # upload which determined the slug/name
  - //quaddicted.com/files/by-sha256/0/00f.../def.zip # alternate upload with a different name
  # a list of files and metadata in the archive
  files:
  - name: maps/abc.bsp
    size: 1234
    modified: 2019-12-01T01:00:00Z
  - name: maps/abc.lit
    size: 12
    modified: 2019-12-01T01:00:00Z
  - name: maps/src/abc.map
    size: 2468
    modified: 2019-12-01T01:00:00Z
  # a repackaged version used by the website
  pak: //quaddicted.com/files/by-sha256/0/00f.../abc.pak 
```

#### Update Map Package
User wants to update the map package for an existing map listing. The map listing will point to the new map package.
```yaml
title: My ABC Map
name: abc
# foreign key now points to the new map package
package:
  name: abc_1a # auto
  hash: 10a... # auto
  modified: 2019-12-02T02:00:00Z # auto, newest file modified timestamp
  # a list of files and metadata in the archive
  files:
  - name: maps/abc.bsp
    size: 1234
    modified: 2019-12-02T02:00:00Z
  urls:
  - //quaddicted.com/files/by-sha256/1/10a.../abc_1a.zip # new version of the map package
  # repacking the new version
  pak: //quaddicted.com/files/by-sha256/1/10a.../abc_1a.pak
```
